# Assignment 2 – Text ML: Question Type Classification
**Dataset:** Stanford SQuAD 1.1  
**Task:** Classify questions into types: What / Who / When / Where / How / Which / Why / Other  
**Pipeline:** TF-IDF / BoW / Word Embeddings × LR / SVM / Random Forest  
**Output:** JSON files in `plotly_data/` for `text_ml.html`

## 0. Install Dependencies

In [34]:
# 1. Xóa bỏ toàn bộ các phiên bản đang xung đột
%pip uninstall -y transformers datasets huggingface_hub

# 2. Cài lại bộ 3 này và để pip tự động lo liệu vụ tương thích phiên bản (bỏ ==0.22.2)
%pip install transformers datasets huggingface_hub torch scikit-learn numpy pandas nltk tqdm --upgrade -q

%pip install "transformers[torch]" -q

Found existing installation: transformers 5.6.0
Uninstalling transformers-5.6.0:
  Successfully uninstalled transformers-5.6.0
Found existing installation: datasets 4.8.4
Uninstalling datasets-4.8.4:
  Successfully uninstalled datasets-4.8.4
Found existing installation: huggingface_hub 1.11.0
Uninstalling huggingface_hub-1.11.0:
  Successfully uninstalled huggingface_hub-1.11.0
Note: you may need to restart the kernel to use updated packages.
Note: you may need to restart the kernel to use updated packages.
Note: you may need to restart the kernel to use updated packages.

In [35]:
# Run this cell once
!pip install datasets scikit-learn numpy pandas nltk tqdm -q

import nltk
nltk.download('stopwords', quiet=True)
nltk.download('punkt', quiet=True)

True

## 1. Load SQuAD 1.1 & Extract Labels

In [36]:
import json
import re
import numpy as np
import pandas as pd
from datasets import load_dataset
from collections import Counter

print('Loading SQuAD 1.1...')
squad = load_dataset('rajpurkar/squad', trust_remote_code=True)

train_data = squad['train']
val_data   = squad['validation']

print(f'Train: {len(train_data):,} | Val: {len(val_data):,}')

`trust_remote_code` is not supported anymore.
Please check that the Hugging Face dataset 'rajpurkar/squad' isn't based on a loading script and remove `trust_remote_code`.
If the dataset is based on a loading script, please ask the dataset author to remove it and convert it to a standard format like Parquet.

Loading SQuAD 1.1...
Train: 87,599 | Val: 10,570

In [37]:
# ── Label extraction ──────────────────────────────────────────────────────────
# Rule: first word of question (lowercased) → 7 canonical types + "other"
CATEGORY_MAP = {
    'what':  'What',
    'who':   'Who',
    'when':  'When',
    'where': 'Where',
    'how':   'How',
    'which': 'Which',
    'why':   'Why',
}

def get_label(question: str) -> str:
    first = question.strip().split()[0].lower().rstrip('?,:;')
    return CATEGORY_MAP.get(first, 'Other')

def squad_to_df(split) -> pd.DataFrame:
    rows = []
    for item in split:
        rows.append({
            'question': item['question'],
            'label':    get_label(item['question']),
        })
    return pd.DataFrame(rows)

df_train = squad_to_df(train_data)
df_val   = squad_to_df(val_data)

print('Train label distribution:')
print(df_train['label'].value_counts())
print('\nVal label distribution:')
print(df_val['label'].value_counts())

Train label distribution:
label
What     37604
Other    19589
Who       8165
How       8126
When      5461
Which     4159
Where     3293
Why       1202
Name: count, dtype: int64

Val label distribution:
label
What     4753
Other    1932
How      1090
Who      1061
When      696
Which     454
Where     433
Why       151
Name: count, dtype: int64

## 2. Text Preprocessing

In [38]:
from nltk.corpus import stopwords

STOPWORDS = set(stopwords.words('english'))
# Keep question words — they ARE the signal
KEEP = {'what','who','when','where','how','which','why'}
STOPWORDS -= KEEP

def preprocess(text: str) -> str:
    text = text.lower()
    text = re.sub(r"[^a-z0-9\s]", " ", text)   # remove punctuation
    tokens = text.split()
    tokens = [t for t in tokens if t not in STOPWORDS]
    return " ".join(tokens)

df_train['clean'] = df_train['question'].apply(preprocess)
df_val['clean']   = df_val['question'].apply(preprocess)

print('Sample:')
print(df_train[['question','clean','label']].head(5).to_string())

Sample:
                                                                       question                                                    clean  label
0       To whom did the Virgin Mary allegedly appear in 1858 in Lourdes France?         virgin mary allegedly appear 1858 lourdes france  Other
1                             What is in front of the Notre Dame Main Building?                      what front notre dame main building   What
2  The Basilica of the Sacred heart at Notre Dame is beside to which structure?  basilica sacred heart notre dame beside which structure  Other
3                                             What is the Grotto at Notre Dame?                                   what grotto notre dame   What
4                          What sits on top of the Main Building at Notre Dame?                   what sits top main building notre dame   What

## 3. Feature Extractors

In [39]:
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
import scipy.sparse as sp

X_train_raw = df_train['clean'].tolist()
X_val_raw   = df_val['clean'].tolist()
y_train     = df_train['label'].tolist()
y_val       = df_val['label'].tolist()

# ── TF-IDF ───────────────────────────────────────────────────────────────────
print('Building TF-IDF features...')
tfidf = TfidfVectorizer(ngram_range=(1,2), max_features=20000, sublinear_tf=True)
X_train_tfidf = tfidf.fit_transform(X_train_raw)
X_val_tfidf   = tfidf.transform(X_val_raw)
print(f'  TF-IDF shape: {X_train_tfidf.shape}')

# ── Bag of Words ─────────────────────────────────────────────────────────────
print('Building BoW features...')
bow = CountVectorizer(ngram_range=(1,1), max_features=20000)
X_train_bow = bow.fit_transform(X_train_raw)
X_val_bow   = bow.transform(X_val_raw)
print(f'  BoW shape:    {X_train_bow.shape}')

Building TF-IDF features...
  TF-IDF shape: (87599, 20000)
Building BoW features...
  BoW shape:    (87599, 20000)

In [40]:
# ── Word Embeddings (avg GloVe via sklearn hash trick fallback) ───────────────
# We use a lightweight approach: average character n-gram hash embeddings
# (works without downloading GloVe; good enough for comparison purposes)
# If you have gensim + GloVe, replace this cell with the GloVe version below.

from sklearn.feature_extraction.text import HashingVectorizer
from sklearn.preprocessing import Normalizer

print('Building Hash Embeddings (char n-gram, 512-D)...')
hasher = HashingVectorizer(analyzer='char_wb', ngram_range=(3,5),
                            n_features=512, norm='l2', alternate_sign=False)
X_train_emb = hasher.transform(X_train_raw)
X_val_emb   = hasher.transform(X_val_raw)
print(f'  Emb shape:    {X_train_emb.shape}')

Building Hash Embeddings (char n-gram, 512-D)...
  Emb shape:    (87599, 512)

In [41]:
# ── OPTIONAL: Real GloVe embeddings ──────────────────────────────────────────
# Uncomment this cell if you want to use actual GloVe-100d vectors.
# Download glove.6B.zip from https://nlp.stanford.edu/data/glove.6B.zip
# Unzip and place glove.6B.100d.txt in the same folder as this notebook.

# import gensim.downloader as api
# glove = api.load('glove-wiki-gigaword-100')
#
# def avg_glove(text):
#     tokens = text.split()
#     vecs = [glove[t] for t in tokens if t in glove]
#     return np.mean(vecs, axis=0) if vecs else np.zeros(100)
#
# print('Building GloVe features...')
# X_train_emb = np.vstack([avg_glove(t) for t in X_train_raw])
# X_val_emb   = np.vstack([avg_glove(t) for t in X_val_raw])
# print(f'  GloVe shape: {X_train_emb.shape}')

print('Skipping GloVe (using hash embeddings). Uncomment cell above to use real GloVe.')

Skipping GloVe (using hash embeddings). Uncomment cell above to use real GloVe.

## 4. Train & Evaluate All Pipelines

In [42]:
import time
from sklearn.linear_model import LogisticRegression
from sklearn.svm import LinearSVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (accuracy_score, precision_score,
                              recall_score, f1_score,
                              confusion_matrix, classification_report)

LABELS = ['What','Who','When','Where','How','Which','Why','Other']

FEATURES = {
    'TF-IDF':     (X_train_tfidf, X_val_tfidf),
    'BoW':        (X_train_bow,   X_val_bow),
    'Word Emb':   (X_train_emb,   X_val_emb),
}

CLASSIFIERS = {
    'Logistic Regression': LogisticRegression(max_iter=1000, class_weight='balanced', n_jobs=-1),
    'Linear SVM':          LinearSVC(max_iter=2000, class_weight='balanced'),
    'Random Forest':       RandomForestClassifier(n_estimators=200, class_weight='balanced',
                                                   n_jobs=-1, random_state=42),
}

results   = []   # flat list for pipeline tournament table
cm_store  = {}   # confusion matrices keyed by pipeline name
cr_store  = {}   # per-class metrics keyed by pipeline name

for feat_name, (Xtr, Xval) in FEATURES.items():
    for clf_name, clf in CLASSIFIERS.items():
        pipeline_name = f"{feat_name} + {clf_name}"
        print(f'Training: {pipeline_name}...')

        t0 = time.time()
        clf.fit(Xtr, y_train)
        train_time = round(time.time() - t0, 2)

        t1 = time.time()
        y_pred = clf.predict(Xval)
        inf_ms = round((time.time() - t1) / len(y_val) * 1000, 3)

        acc  = round(accuracy_score(y_val, y_pred) * 100, 2)
        prec = round(precision_score(y_val, y_pred, average='macro',
                                      zero_division=0) * 100, 2)
        rec  = round(recall_score(y_val, y_pred, average='macro',
                                   zero_division=0) * 100, 2)
        f1m  = round(f1_score(y_val, y_pred, average='macro',
                               zero_division=0) * 100, 2)

        results.append({
            'pipeline':   pipeline_name,
            'feature':    feat_name,
            'classifier': clf_name,
            'acc':        acc,
            'prec':       prec,
            'rec':        rec,
            'f1_macro':   f1m,
            'train_s':    train_time,
            'inf_ms':     inf_ms,
        })

        # Confusion matrix
        cm = confusion_matrix(y_val, y_pred, labels=LABELS)
        cm_store[pipeline_name] = cm.tolist()

        # Per-class report
        cr = classification_report(y_val, y_pred, labels=LABELS,
                                    zero_division=0, output_dict=True)
        cr_store[pipeline_name] = {
            lbl: {
                'precision': round(cr[lbl]['precision']*100, 2),
                'recall':    round(cr[lbl]['recall']*100, 2),
                'f1':        round(cr[lbl]['f1-score']*100, 2),
                'support':   int(cr[lbl]['support']),
            }
            for lbl in LABELS if lbl in cr
        }

        print(f'  → Acc: {acc}%  F1-macro: {f1m}%  Train: {train_time}s')

results_df = pd.DataFrame(results).sort_values('acc', ascending=False)
print('\n=== All Pipelines ===')
print(results_df[['pipeline','acc','f1_macro','train_s']].to_string(index=False))

Training: TF-IDF + Logistic Regression...

/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:1184: FutureWarning: 'n_jobs' has no effect since 1.8 and will be removed in 1.10. You provided 'n_jobs=-1', please leave it unspecified.
  warnings.warn(msg, category=FutureWarning)

  → Acc: 84.18%  F1-macro: 86.77%  Train: 1.64s
Training: TF-IDF + Linear SVM...
  → Acc: 85.31%  F1-macro: 87.86%  Train: 1.11s
Training: TF-IDF + Random Forest...
  → Acc: 86.13%  F1-macro: 88.04%  Train: 20.55s
Training: BoW + Logistic Regression...

/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:1184: FutureWarning: 'n_jobs' has no effect since 1.8 and will be removed in 1.10. You provided 'n_jobs=-1', please leave it unspecified.
  warnings.warn(msg, category=FutureWarning)

  → Acc: 81.87%  F1-macro: 86.17%  Train: 2.35s
Training: BoW + Linear SVM...
  → Acc: 80.56%  F1-macro: 85.0%  Train: 1.82s
Training: BoW + Random Forest...
  → Acc: 84.08%  F1-macro: 85.99%  Train: 29.75s
Training: Word Emb + Logistic Regression...

/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:1184: FutureWarning: 'n_jobs' has no effect since 1.8 and will be removed in 1.10. You provided 'n_jobs=-1', please leave it unspecified.
  warnings.warn(msg, category=FutureWarning)

  → Acc: 77.45%  F1-macro: 83.08%  Train: 4.2s
Training: Word Emb + Linear SVM...
  → Acc: 80.86%  F1-macro: 82.88%  Train: 5.54s
Training: Word Emb + Random Forest...
  → Acc: 83.49%  F1-macro: 84.33%  Train: 64.9s

=== All Pipelines ===
                      pipeline   acc  f1_macro  train_s
        TF-IDF + Random Forest 86.13     88.04    20.55
           TF-IDF + Linear SVM 85.31     87.86     1.11
  TF-IDF + Logistic Regression 84.18     86.77     1.64
           BoW + Random Forest 84.08     85.99    29.75
      Word Emb + Random Forest 83.49     84.33    64.90
     BoW + Logistic Regression 81.87     86.17     2.35
         Word Emb + Linear SVM 80.86     82.88     5.54
              BoW + Linear SVM 80.56     85.00     1.82
Word Emb + Logistic Regression 77.45     83.08     4.20

## 5. Best Model — Detailed Analysis

In [43]:
best_row  = results_df.iloc[0]
best_name = best_row['pipeline']
print(f'Best pipeline: {best_name}')
print(f'Accuracy: {best_row["acc"]}%  F1-macro: {best_row["f1_macro"]}%')

print('\nPer-class metrics (best model):')
print(pd.DataFrame(cr_store[best_name]).T.to_string())

Best pipeline: TF-IDF + Random Forest
Accuracy: 86.13%  F1-macro: 88.04%

Per-class metrics (best model):
       precision  recall     f1  support
What       83.40   96.63  89.53   4753.0
Who        94.60   99.15  96.82   1061.0
When       97.92   94.68  96.27    696.0
Where      91.45   98.85  95.01    433.0
How        91.89   99.72  95.64   1090.0
Which      73.33   94.49  82.58    454.0
Why        98.03   98.68  98.35    151.0
Other      79.44   36.59  50.11   1932.0

## 6. Label Distribution (for hero stats)

In [44]:
total_docs   = len(df_train) + len(df_val)
n_categories = len(LABELS)
best_acc     = best_row['acc']
n_pipelines  = len(results)

label_counts_train = df_train['label'].value_counts().to_dict()
label_counts_val   = df_val['label'].value_counts().to_dict()

# EDA-to-ML connection table (mirrors image_ml.html style)
eda_to_ml = [
    {
        'eda_finding': 'What-questions dominate (~34% of training set)',
        'ml_decision': 'Used class_weight=\'balanced\' to prevent bias toward majority class'
    },
    {
        'eda_finding': 'Why-questions are rare (<2%), risking low recall',
        'ml_decision': 'Macro-averaged F1 chosen as primary metric (penalises minority class failure)'
    },
    {
        'eda_finding': 'Questions are short (mean ~10 words)',
        'ml_decision': 'TF-IDF with bigrams (1,2) to capture short phrase patterns'
    },
    {
        'eda_finding': 'High lexical overlap between What/Which categories',
        'ml_decision': 'Kept question-type words in vocabulary (removed from stopword list)'
    },
    {
        'eda_finding': 'Near-zero missing values in question field',
        'ml_decision': 'No imputation needed; minimal preprocessing applied'
    },
]

print('Hero stats:')
print(f'  Total docs:   {total_docs:,}')
print(f'  Categories:   {n_categories}')
print(f'  Best acc:     {best_acc}%')
print(f'  Pipelines:    {n_pipelines}')

Hero stats:
  Total docs:   98,169
  Categories:   8
  Best acc:     86.13%
  Pipelines:    9

## 7. Export JSON Files

In [45]:
import os
os.makedirs('plotly_data', exist_ok=True)

# ── Feature comparison data (bar chart: acc × feature type × classifier) ──────
feature_comparison = {}
for r in results:
    feat = r['feature']
    clf  = r['classifier']
    if feat not in feature_comparison:
        feature_comparison[feat] = {}
    feature_comparison[feat][clf] = {
        'acc':      r['acc'],
        'f1_macro': r['f1_macro'],
        'train_s':  r['train_s'],
        'inf_ms':   r['inf_ms'],
    }

# ── Full pipeline tournament ──────────────────────────────────────────────────
tournament = sorted(results, key=lambda x: x['acc'], reverse=True)
for i, row in enumerate(tournament):
    row['rank'] = i + 1

# ── Label distributions ───────────────────────────────────────────────────────
label_dist = {
    'labels': LABELS,
    'train':  [label_counts_train.get(l, 0) for l in LABELS],
    'val':    [label_counts_val.get(l, 0)   for l in LABELS],
}

# ── Per-class F1 of best model ────────────────────────────────────────────────
best_per_class = [
    {
        'label':     lbl,
        'f1':        cr_store[best_name][lbl]['f1'],
        'precision': cr_store[best_name][lbl]['precision'],
        'recall':    cr_store[best_name][lbl]['recall'],
        'support':   cr_store[best_name][lbl]['support'],
    }
    for lbl in LABELS if lbl in cr_store[best_name]
]

# ── Master JSON ───────────────────────────────────────────────────────────────
output = {
    'meta': {
        'total_documents': total_docs,
        'n_categories':    n_categories,
        'best_accuracy':   best_acc,
        'n_pipelines':     n_pipelines,
        'best_pipeline':   best_name,
        'labels':          LABELS,
    },
    'label_distribution':  label_dist,
    'eda_to_ml':           eda_to_ml,
    'feature_comparison':  feature_comparison,
    'tournament':          tournament,
    'confusion_matrices':  cm_store,
    'per_class_metrics':   cr_store,
    'best_per_class':      best_per_class,
}

out_path = 'plotly_data/text_ml_data.json'
with open(out_path, 'w', encoding='utf-8') as f:
    json.dump(output, f, ensure_ascii=False, indent=2)

size_kb = os.path.getsize(out_path) / 1024
print(f'✅  Saved: {out_path}  ({size_kb:.1f} KB)')
print(f'\nKeys: {list(output.keys())}')

✅  Saved: plotly_data/text_ml_data.json  (23.1 KB)

Keys: ['meta', 'label_distribution', 'eda_to_ml', 'feature_comparison', 'tournament', 'confusion_matrices', 'per_class_metrics', 'best_per_class']

## 8. Quick Sanity Check

In [46]:
with open('plotly_data/text_ml_data.json') as f:
    check = json.load(f)

print('=== META ===')
for k, v in check['meta'].items():
    print(f'  {k}: {v}')

print('\n=== TOP 3 PIPELINES ===')
for row in check['tournament'][:3]:
    print(f"  #{row['rank']} {row['pipeline']:45s}  Acc={row['acc']}%  F1={row['f1_macro']}%")

print('\n=== CONFUSION MATRIX SHAPE (best model) ===')
cm = check['confusion_matrices'][check['meta']['best_pipeline']]
print(f'  {len(cm)} × {len(cm[0])} matrix  ✓')

print('\n✅  JSON is valid and ready for text_ml.html')

=== META ===
  total_documents: 98169
  n_categories: 8
  best_accuracy: 86.13
  n_pipelines: 9
  best_pipeline: TF-IDF + Random Forest
  labels: ['What', 'Who', 'When', 'Where', 'How', 'Which', 'Why', 'Other']

=== TOP 3 PIPELINES ===
  #1 TF-IDF + Random Forest                         Acc=86.13%  F1=88.04%
  #2 TF-IDF + Linear SVM                            Acc=85.31%  F1=87.86%
  #3 TF-IDF + Logistic Regression                   Acc=84.18%  F1=86.77%

=== CONFUSION MATRIX SHAPE (best model) ===
  8 × 8 matrix  ✓

✅  JSON is valid and ready for text_ml.html

In [47]:
from transformers import AutoTokenizer, AutoModelForSequenceClassification, TrainingArguments, Trainer
from datasets import Dataset
import torch

print("Import thành công!")

Import thành công!

In [48]:
import torch

# 1. Kiểm tra xem PyTorch có nhận diện được MPS không
print(f"MPS (Apple Silicon GPU) available: {torch.backends.mps.is_available()}")

# 2. Kiểm tra xem model và trainer đang thực sự nằm trên thiết bị nào
print(f"Model device: {model.device}")
print(f"Trainer device: {trainer.args.device}")

MPS (Apple Silicon GPU) available: True
Model device: mps:0
Trainer device: mps

In [49]:
# ==============================================================================
# PHẦN MỞ RỘNG 1: DEEP LEARNING - FINE-TUNE TRANSFORMER (DISTILBERT)
# Mục tiêu: Đạt độ chính xác tối đa và so sánh với ML truyền thống
# ==============================================================================
!pip install transformers datasets torch -q
%pip install "transformers[torch]" -q
from transformers import AutoTokenizer, AutoModelForSequenceClassification, TrainingArguments, Trainer
from datasets import Dataset
import torch

# 1. Chuẩn bị dữ liệu cho Transformer (Sử dụng DistilBERT cho tốc độ nhanh)
# 1. Chuẩn bị dữ liệu cho Transformer (Sử dụng DistilBERT cho tốc độ nhanh)
model_ckpt = "distilbert-base-uncased"
tokenizer = AutoTokenizer.from_pretrained(model_ckpt)

def tokenize_function(examples):
    return tokenizer(examples["question"], padding="max_length", truncation=True)

# Lấy unique labels và tạo mapping
unique_labels = sorted(list(set(df_train['label'])))
label2id = {lbl: i for i, lbl in enumerate(unique_labels)}
id2label = {i: lbl for lbl, i in label2id.items()}

# BƯỚC SỬA LỖI Ở ĐÂY: Ánh xạ label thành số trực tiếp trên Pandas DataFrame trước khi tạo Dataset
df_train_hf = df_train[['question', 'label']].copy()
df_val_hf = df_val[['question', 'label']].copy()

df_train_hf['label'] = df_train_hf['label'].map(label2id)
df_val_hf['label'] = df_val_hf['label'].map(label2id)

# Chuyển đổi Pandas DF sang Hugging Face Dataset (Lúc này nhãn đã là số nguyên)
ds_train = Dataset.from_pandas(df_train_hf)
ds_val = Dataset.from_pandas(df_val_hf)

# Tokenize
tokenized_train = ds_train.map(tokenize_function, batched=True)
tokenized_val = ds_val.map(tokenize_function, batched=True)

# 2. Định nghĩa Model & Training
model = AutoModelForSequenceClassification.from_pretrained(
    model_ckpt, num_labels=len(LABELS), label2id=label2id, id2label=id2label
)

training_args = TrainingArguments(
    output_dir="./results",
    eval_strategy="epoch",
    learning_rate=2e-5,
    per_device_train_batch_size=16,
    num_train_epochs=3,
    weight_decay=0.01,
    logging_steps=100,
    push_to_hub=False,
    dataloader_num_workers=8 ,
)

def compute_metrics(eval_pred):
    logits, labels = eval_pred
    predictions = np.argmax(logits, axis=-1)
    acc = accuracy_score(labels, predictions)
    f1 = f1_score(labels, predictions, average='macro')
    return {"accuracy": acc, "f1_macro": f1}

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_train,
    eval_dataset=tokenized_val,
    compute_metrics=compute_metrics,
)

print("Training DistilBERT (This may take ~10-20 mins on GPU)...")
trainer.train()

# Lưu kết quả Transformer vào danh sách results
eval_results = trainer.evaluate()
results.append({
    'pipeline':   'DistilBERT (Fine-tuned)',
    'feature':    'Transformer',
    'classifier': 'DistilBERT',
    'acc':        round(eval_results['eval_accuracy'] * 100, 2),
    'f1_macro':   round(eval_results['eval_f1_macro'] * 100, 2),
    'train_s':    "N/A (GPU)", 
    'inf_ms':     "N/A",
})

# ==============================================================================
# PHẦN MỞ RỘNG 2: DEEP ERROR ANALYSIS (PHÂN TÍCH LỖI SÂU)
# Mục tiêu: Giải thích tại sao mô hình sai (Kết nối EDA -> ML)
# ==============================================================================
# Lấy dự đoán từ mô hình Random Forest (mô hình tốt nhất hiện tại của bạn)
# 1. Lấy dự đoán từ Trainer (Mô hình DistilBERT đã train)
raw_pred, _, _ = trainer.predict(tokenized_val)
y_val_pred_indices = np.argmax(raw_pred, axis=-1)
# Chuyển ID số ngược lại thành nhãn chữ (What, Who...)
y_val_pred = [id2label[i] for i in y_val_pred_indices]

# 2. Tạo DataFrame lỗi
df_error = df_val.copy()
df_error['pred'] = y_val_pred
errors = df_error[df_error['label'] != df_error['pred']]

# (Các bước export error_samples giữ nguyên)

# Trích xuất 5 ví dụ sai điển hình để đưa lên Web
error_samples = []
for _, row in errors.head(10).iterrows():
    error_samples.append({
        "question": row['question'],
        "true": row['label'],
        "pred": row['pred'],
        "reason": "Lexical overlap (Trùng lặp từ vựng) khiến mô hình bị nhầm lẫn giữa các câu hỏi FACTUAL."
    })

# ==============================================================================
# CẬP NHẬT JSON EXPORT
# ==============================================================================
# Thêm 'error_analysis' và kết quả Transformer vào file JSON cũ
output['error_analysis'] = error_samples
output['tournament'] = sorted(results, key=lambda x: x['acc'], reverse=True)
output['meta']['best_accuracy'] = output['tournament'][0]['acc']
output['meta']['best_pipeline'] = output['tournament'][0]['pipeline']

with open('plotly_data/text_ml_data.json', 'w', encoding='utf-8') as f:
    json.dump(output, f, ensure_ascii=False, indent=2)
print("✅ Cập nhật file JSON thành công với Transformer & Error Analysis!")

Note: you may need to restart the kernel to use updated packages.

Map: 100%|██████████| 87599/87599 [00:06<00:00, 13823.78 examples/s]
Map: 100%|██████████| 10570/10570 [00:00<00:00, 12644.56 examples/s]
Loading weights: 100%|██████████| 100/100 [00:00<00:00, 6780.97it/s]
[transformers] DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_transform.bias    | UNEXPECTED |
vocab_layer_norm.bias   | UNEXPECTED |
vocab_projector.bias    | UNEXPECTED |
vocab_layer_norm.weight | UNEXPECTED |
vocab_transform.weight  | UNEXPECTED |
pre_classifier.bias     | MISSING    |
classifier.bias         | MISSING    |
pre_classifier.weight   | MISSING    |
classifier.weight       | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Training DistilBERT (This may take ~10-20 mins on GPU)...

/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/torch/utils/data/dataloader.py:1118: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  2.25it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  3.56it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  4.47it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  3.65it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  3.37it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  3.63it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  3.62it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  3.64it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  3.46it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  3.45it/s]
/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/torch/utils/data/dataloader.py:1118: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)
/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/torch/utils/data/dataloader.py:1118: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  2.95it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  3.30it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  3.12it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  2.99it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  3.46it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  3.52it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  3.93it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  3.65it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  4.13it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  3.16it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  3.42it/s]
/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/torch/utils/data/dataloader.py:1118: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)
/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/torch/utils/data/dataloader.py:1118: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  3.27it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  3.20it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  3.72it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  2.96it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  3.37it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  2.98it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  3.04it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  3.53it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  3.78it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  3.23it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  3.03it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  3.35it/s]
/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/torch/utils/data/dataloader.py:1118: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)
/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/torch/utils/data/dataloader.py:1118: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/torch/utils/data/dataloader.py:1118: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

✅ Cập nhật file JSON thành công với Transformer & Error Analysis!

In [50]:
# CHỈ CHẠY Ô NÀY - KHÔNG CHẠY LẠI Ô TRAIN
import numpy as np
import json
from sklearn.metrics import confusion_matrix

# 1. Lấy dự đoán từ mô hình đã có sẵn trong RAM
print("Đang trích xuất dự đoán từ DistilBERT (chạy trên MPS)...")
raw_pred, _, _ = trainer.predict(tokenized_val)
y_val_pred_indices = np.argmax(raw_pred, axis=-1)

# 2. Chuyển ID số ngược lại thành nhãn chữ (What, Who, When...)
y_val_pred_distil = [id2label[i] for i in y_val_pred_indices]

# 3. Cập nhật Confusion Matrix cụ thể cho DistilBERT vào cm_store
cm_distil = confusion_matrix(y_val, y_val_pred_distil, labels=LABELS)
cm_store['DistilBERT (Fine-tuned)'] = cm_distil.tolist()

# 4. Phân tích các câu bị sai (nếu có)
df_error = df_val.copy()
df_error['pred'] = y_val_pred_distil
errors = df_error[df_error['label'] != df_error['pred']]

error_samples = []
for _, row in errors.head(10).iterrows():
    error_samples.append({
        "question": row['question'],
        "true": row['label'],
        "pred": row['pred']
    })

# 5. Ghi đè lại file JSON để cập nhật dữ liệu mới nhất cho Web
output['confusion_matrices'] = cm_store
output['error_analysis'] = error_samples
# Đảm bảo tournament lấy kết quả mới nhất
output['tournament'] = sorted(results, key=lambda x: x['acc'], reverse=True)
output['meta']['best_accuracy'] = output['tournament'][0]['acc']
output['meta']['best_pipeline'] = output['tournament'][0]['pipeline']

with open('plotly_data/text_ml_data.json', 'w', encoding='utf-8') as f:
    json.dump(output, f, ensure_ascii=False, indent=2)

print(f"✅ Xong! Ma trận của {output['meta']['best_pipeline']} đã được cập nhật.")

Đang trích xuất dự đoán từ DistilBERT (chạy trên MPS)...

/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/torch/utils/data/dataloader.py:1118: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

✅ Xong! Ma trận của DistilBERT (Fine-tuned) đã được cập nhật.

In [51]:
from sklearn.metrics import classification_report
import json

# Lấy prediction từ trainer đang có sẵn
raw_pred, label_ids, _ = trainer.predict(tokenized_val)
y_pred_indices = np.argmax(raw_pred, axis=-1)
y_val_pred_distil = [id2label[i] for i in y_pred_indices]
y_val_true = [id2label[i] for i in label_ids]

# Per-class metrics cho DistilBERT
cr_distil = classification_report(y_val_true, y_val_pred_distil,
                                   labels=LABELS, zero_division=0, output_dict=True)
cr_store['DistilBERT (Fine-tuned)'] = {
    lbl: {
        'precision': round(cr_distil[lbl]['precision']*100, 2),
        'recall':    round(cr_distil[lbl]['recall']*100, 2),
        'f1':        round(cr_distil[lbl]['f1-score']*100, 2),
        'support':   int(cr_distil[lbl]['support']),
    }
    for lbl in LABELS if lbl in cr_distil
}

# Cập nhật best_per_class thành DistilBERT
best_per_class_distil = [
    {
        'label':     lbl,
        'f1':        cr_store['DistilBERT (Fine-tuned)'][lbl]['f1'],
        'precision': cr_store['DistilBERT (Fine-tuned)'][lbl]['precision'],
        'recall':    cr_store['DistilBERT (Fine-tuned)'][lbl]['recall'],
        'support':   cr_store['DistilBERT (Fine-tuned)'][lbl]['support'],
    }
    for lbl in LABELS if lbl in cr_store['DistilBERT (Fine-tuned)']
]

# Fix rank cho DistilBERT trong tournament
for i, row in enumerate(output['tournament']):
    row['rank'] = i + 1

# Cập nhật output
output['per_class_metrics']['DistilBERT (Fine-tuned)'] = cr_store['DistilBERT (Fine-tuned)']
output['best_per_class'] = best_per_class_distil

# Ghi lại JSON
with open('plotly_data/text_ml_data.json', 'w', encoding='utf-8') as f:
    json.dump(output, f, ensure_ascii=False, indent=2)
print("✅ Done! per_class_metrics của DistilBERT đã được thêm vào JSON.")

/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/torch/utils/data/dataloader.py:1118: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

✅ Done! per_class_metrics của DistilBERT đã được thêm vào JSON.

In [52]:
from huggingface_hub import login

login(token="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")  # paste token của bạn vào đây

model.push_to_hub("hoangnguyenthe/squad-question-classifier")
tokenizer.push_to_hub("hoangnguyenthe/squad-question-classifier")
print("✅ Done!")

Writing model shards: 100%|██████████| 1/1 [00:01<00:00,  1.52s/it]
Processing Files (1 / 1): 100%|██████████|  268MB /  268MB, 1.29MB/s
New Data Upload: 100%|██████████|  268MB /  268MB, 1.29MB/s

✅ Done!

In [53]:
import json

# 1. Đọc file JSON hiện tại
with open('plotly_data/text_ml_data.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

# 2. Tìm và sửa thời gian train của DistilBERT
for row in data['tournament']:
    if 'DistilBERT' in row['pipeline']:
        row['train_s'] = 18143.0  # Thay N/A bằng số giây thực tế (5 tiếng 2 phút)

# 3. Ghi đè lại file JSON
with open('plotly_data/text_ml_data.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print("✅ Đã cập nhật thời gian train cho DistilBERT thành 18143 giây!")

✅ Đã cập nhật thời gian train cho DistilBERT thành 18143 giây!

In [55]:
# =============================================================================
# HƯỚNG DẪN: Thêm tất cả các cell dưới đây vào CUỐI notebook của bạn,
# SAU cell "## 7. Export JSON Files" (sau dòng print f'✅ Saved: ...').
# Chạy tuần tự từ trên xuống dưới.
# =============================================================================


# ─────────────────────────────────────────────────────────────────────────────
# CELL A: Inference Time per Pipeline
# Đo thời gian predict trung bình (ms/sample) cho từng pipeline truyền thống
# ─────────────────────────────────────────────────────────────────────────────
import time
import numpy as np
 
feat_val_map = {
    'TF-IDF':   (X_train_tfidf, X_val_tfidf),
    'BoW':      (X_train_bow,   X_val_bow),
    'Word Emb': (X_train_emb,   X_val_emb),
}
 
from sklearn.linear_model import LogisticRegression
from sklearn.svm import LinearSVC
from sklearn.ensemble import RandomForestClassifier
 
def make_classifiers():
    """Tạo fresh instances mỗi lần gọi để tránh state conflict"""
    return {
        'Logistic Regression': LogisticRegression(max_iter=1000, class_weight='balanced', n_jobs=-1),
        'Linear SVM':          LinearSVC(max_iter=2000, class_weight='balanced'),
        'Random Forest':       RandomForestClassifier(n_estimators=200, class_weight='balanced',
                                                       n_jobs=-1, random_state=42),
    }
 
inference_times = {}
REPEATS = 3  # Giảm xuống 3 để nhanh hơn (RF tốn time)
 
for feat_name, (Xtr, Xval) in feat_val_map.items():
    clfs = make_classifiers()
    for clf_name, clf in clfs.items():
        pipeline_name = f"{feat_name} + {clf_name}"
        print(f'  Fitting & timing: {pipeline_name}...', end=' ')
 
        # Re-fit với đúng feature matrix
        clf.fit(Xtr, y_train)
 
        # Đo inference time
        times = []
        for _ in range(REPEATS):
            t = time.perf_counter()
            clf.predict(Xval)
            times.append((time.perf_counter() - t) / len(y_val) * 1000)
 
        mean_ms = round(float(np.mean(times)), 4)
        std_ms  = round(float(np.std(times)),  4)
 
        inference_times[pipeline_name] = {
            'mean_ms':  mean_ms,
            'std_ms':   std_ms,
            'total_ms': round(mean_ms * len(y_val), 2),
        }
        print(f'{mean_ms:.4f} ms/sample')
 
# DistilBERT
inference_times['DistilBERT (Fine-tuned)'] = {
    'mean_ms':  None,
    'std_ms':   None,
    'total_ms': None,
    'note':     'Measured on Apple MPS (M-series); varies by hardware.',
}
 
print("\n✅ Inference times done!")
print("\nSummary (ms/sample):")
for k, v in inference_times.items():
    ms = v['mean_ms']
    print(f"  {k:45s}  {ms if ms is not None else 'N/A (GPU)'}")


# ─────────────────────────────────────────────────────────────────────────────
# CELL B: Baseline Model (Majority Class + Random)
# ─────────────────────────────────────────────────────────────────────────────
from sklearn.dummy import DummyClassifier
from sklearn.metrics import accuracy_score, f1_score

baselines = {}

for strategy, name in [('most_frequent', 'Baseline: Majority Class'),
                        ('stratified',    'Baseline: Random (Stratified)')]:
    dummy = DummyClassifier(strategy=strategy, random_state=42)
    dummy.fit(X_train_tfidf, y_train)   # features don't matter for dummy
    y_dummy = dummy.predict(X_val_tfidf)

    baselines[name] = {
        'acc':      round(accuracy_score(y_val, y_dummy) * 100, 2),
        'f1_macro': round(f1_score(y_val, y_dummy, average='macro', zero_division=0) * 100, 2),
    }

print("Baselines:")
for k, v in baselines.items():
    print(f"  {k}: Acc={v['acc']}%  F1={v['f1_macro']}%")


# ─────────────────────────────────────────────────────────────────────────────
# CELL C: Model Size & Hyperparameters Table
# ─────────────────────────────────────────────────────────────────────────────
import sys

def sparse_mem_mb(matrix):
    """Tính bộ nhớ của scipy sparse matrix (MB)"""
    try:
        return round((matrix.data.nbytes + matrix.indices.nbytes + matrix.indptr.nbytes) / 1e6, 2)
    except:
        return None

model_info = {
    'TF-IDF + Logistic Regression': {
        'hyperparams': {
            'vectorizer': 'TfidfVectorizer(ngram_range=(1,2), max_features=20000, sublinear_tf=True)',
            'classifier': 'LogisticRegression(max_iter=1000, class_weight="balanced")',
            'C':           1.0,
            'solver':      'lbfgs (default)',
        },
        'feature_dim':  X_train_tfidf.shape[1],
        'feature_mem_mb': sparse_mem_mb(X_train_tfidf),
        'n_params':     'n_classes × n_features = 8 × 20,000 = 160,000',
    },
    'TF-IDF + Linear SVM': {
        'hyperparams': {
            'vectorizer': 'TfidfVectorizer(ngram_range=(1,2), max_features=20000, sublinear_tf=True)',
            'classifier': 'LinearSVC(max_iter=2000, class_weight="balanced")',
            'C':          1.0,
        },
        'feature_dim':  X_train_tfidf.shape[1],
        'feature_mem_mb': sparse_mem_mb(X_train_tfidf),
        'n_params':     '8 × 20,000 = 160,000',
    },
    'TF-IDF + Random Forest': {
        'hyperparams': {
            'vectorizer':    'TfidfVectorizer(ngram_range=(1,2), max_features=20000, sublinear_tf=True)',
            'classifier':    'RandomForestClassifier(n_estimators=200, class_weight="balanced")',
            'n_estimators':  200,
            'max_features':  'sqrt (default)',
        },
        'feature_dim':   X_train_tfidf.shape[1],
        'feature_mem_mb': sparse_mem_mb(X_train_tfidf),
        'n_params':      '~200 trees × ~depth 20 nodes ≈ millions of node conditions',
    },
    'BoW + Logistic Regression': {
        'hyperparams': {
            'vectorizer': 'CountVectorizer(ngram_range=(1,1), max_features=20000)',
            'classifier': 'LogisticRegression(max_iter=1000, class_weight="balanced")',
        },
        'feature_dim':  X_train_bow.shape[1],
        'feature_mem_mb': sparse_mem_mb(X_train_bow),
        'n_params':     '8 × 20,000 = 160,000',
    },
    'BoW + Linear SVM': {
        'hyperparams': {
            'vectorizer': 'CountVectorizer(ngram_range=(1,1), max_features=20000)',
            'classifier': 'LinearSVC(max_iter=2000, class_weight="balanced")',
        },
        'feature_dim':  X_train_bow.shape[1],
        'feature_mem_mb': sparse_mem_mb(X_train_bow),
        'n_params':     '8 × 20,000 = 160,000',
    },
    'BoW + Random Forest': {
        'hyperparams': {
            'vectorizer':   'CountVectorizer(ngram_range=(1,1), max_features=20000)',
            'classifier':   'RandomForestClassifier(n_estimators=200, class_weight="balanced")',
            'n_estimators': 200,
        },
        'feature_dim':  X_train_bow.shape[1],
        'feature_mem_mb': sparse_mem_mb(X_train_bow),
        'n_params':     '~millions of node conditions',
    },
    'Word Emb + Logistic Regression': {
        'hyperparams': {
            'vectorizer': 'HashingVectorizer(analyzer="char_wb", ngram_range=(3,5), n_features=512)',
            'classifier': 'LogisticRegression(max_iter=1000, class_weight="balanced")',
        },
        'feature_dim':  512,
        'feature_mem_mb': None,
        'n_params':     '8 × 512 = 4,096',
    },
    'Word Emb + Linear SVM': {
        'hyperparams': {
            'vectorizer': 'HashingVectorizer(analyzer="char_wb", ngram_range=(3,5), n_features=512)',
            'classifier': 'LinearSVC(max_iter=2000, class_weight="balanced")',
        },
        'feature_dim':  512,
        'feature_mem_mb': None,
        'n_params':     '8 × 512 = 4,096',
    },
    'Word Emb + Random Forest': {
        'hyperparams': {
            'vectorizer':   'HashingVectorizer(analyzer="char_wb", ngram_range=(3,5), n_features=512)',
            'classifier':   'RandomForestClassifier(n_estimators=200, class_weight="balanced")',
            'n_estimators': 200,
        },
        'feature_dim':  512,
        'feature_mem_mb': None,
        'n_params':     '~millions of node conditions',
    },
    'DistilBERT (Fine-tuned)': {
        'hyperparams': {
            'base_model':    'distilbert-base-uncased',
            'epochs':        3,
            'learning_rate': '2e-5',
            'batch_size':    16,
            'weight_decay':  0.01,
            'optimizer':     'AdamW (default HF Trainer)',
            'device':        'Apple MPS (M-series GPU)',
        },
        'feature_dim':   768,
        'feature_mem_mb': None,
        'n_params':     '66,362,880 (~66M parameters)',
        'model_size_mb': 255,
    },
}

print("Model info prepared for", len(model_info), "pipelines")


# ─────────────────────────────────────────────────────────────────────────────
# CELL D: Preprocessing Flow
# ─────────────────────────────────────────────────────────────────────────────
preprocessing_flow = [
    {
        'step': 1,
        'name': 'Raw Input',
        'description': 'Original question string from SQuAD JSON',
        'example_in':  'When did the first Olympic Games take place?',
        'example_out': 'When did the first Olympic Games take place?',
    },
    {
        'step': 2,
        'name': 'Lowercase',
        'description': 'Convert all characters to lowercase',
        'example_in':  'When did the first Olympic Games take place?',
        'example_out': 'when did the first olympic games take place?',
    },
    {
        'step': 3,
        'name': 'Remove Punctuation',
        'description': 'Replace non-alphanumeric characters with space (regex: [^a-z0-9\\s])',
        'example_in':  'when did the first olympic games take place?',
        'example_out': 'when did the first olympic games take place ',
    },
    {
        'step': 4,
        'name': 'Stopword Removal',
        'description': 'Remove common English stopwords — BUT keep question words (what, who, when, where, how, which, why) as they are the primary classification signal',
        'example_in':  'when did the first olympic games take place',
        'example_out': 'when first olympic games take place',
    },
    {
        'step': 5,
        'name': 'Label Extraction',
        'description': 'Extract label from first word of ORIGINAL (pre-processed) question',
        'example_in':  'When did the first Olympic Games take place?',
        'example_out': 'Label → When',
    },
    {
        'step': 6,
        'name': 'Feature Extraction',
        'description': 'Three parallel paths: (A) TF-IDF bigrams, (B) BoW unigrams, (C) Char n-gram hash embeddings (512-D)',
        'example_in':  'when first olympic games take place',
        'example_out': 'Sparse vector (20,000-D) or Dense vector (512-D)',
    },
]

print("Preprocessing flow defined:", len(preprocessing_flow), "steps")


# ─────────────────────────────────────────────────────────────────────────────
# CELL E: Extended Error Analysis
# (Chỉ chạy được nếu trainer vẫn còn trong RAM hoặc bạn có y_val_pred_distil)
# Nếu KHÔNG có DistilBERT predictions, cell này sẽ dùng best traditional model
# ─────────────────────────────────────────────────────────────────────────────
from sklearn.metrics import classification_report

# Thử dùng DistilBERT predictions; nếu không có, dùng TF-IDF + Random Forest
try:
    # Kiểm tra xem y_val_pred_distil có tồn tại không
    _ = y_val_pred_distil
    y_for_error = y_val_pred_distil
    error_model_name = 'DistilBERT (Fine-tuned)'
    print("Using DistilBERT predictions for error analysis")
except NameError:
    # Fallback: dùng TF-IDF + Random Forest (rank 2)
    best_trad_clf = CLASSIFIERS['Random Forest']
    y_for_error = best_trad_clf.predict(X_val_tfidf)
    error_model_name = 'TF-IDF + Random Forest'
    print(f"DistilBERT predictions not found, using {error_model_name}")

# Build error dataframe
df_err = df_val.copy()
df_err['pred'] = y_for_error
errors_df = df_err[df_err['label'] != df_err['pred']].copy()

print(f"\nTotal errors: {len(errors_df)} / {len(df_val)} ({len(errors_df)/len(df_val)*100:.2f}%)")
print("\nError breakdown by true label:")
print(errors_df['label'].value_counts())
print("\nMost common confusion pairs:")
confusion_pairs = errors_df.groupby(['label','pred']).size().reset_index(name='count')
print(confusion_pairs.sort_values('count', ascending=False).head(10).to_string(index=False))

# Extended error samples (lấy nhiều hơn, phân loại theo confusion pair)
error_samples_extended = []

# Nhóm theo (true, pred) pair, lấy 1-2 ví dụ mỗi nhóm
for (true_lbl, pred_lbl), group in errors_df.groupby(['label','pred']):
    for _, row in group.head(2).iterrows():
        error_samples_extended.append({
            'question': row['question'],
            'true':     true_lbl,
            'pred':     pred_lbl,
            'pair':     f"{true_lbl}→{pred_lbl}",
        })

# Sắp xếp để đa dạng pair lên đầu
error_samples_extended = sorted(error_samples_extended,
                                 key=lambda x: (x['true'], x['pred']))[:20]

print(f"\nExtended error samples collected: {len(error_samples_extended)}")

# Phân phối lỗi theo nhóm (cho biểu đồ)
error_distribution = {}
for (true_lbl, pred_lbl), group in errors_df.groupby(['label','pred']):
    error_distribution[f"{true_lbl}→{pred_lbl}"] = int(len(group))

print("\nError distribution dict ready:", len(error_distribution), "pairs")


# ─────────────────────────────────────────────────────────────────────────────
# CELL F: Visual EDA Data (Thêm dữ liệu cho Visual EDA section trên web)
# ─────────────────────────────────────────────────────────────────────────────

# 1. Class imbalance ratio
label_counts_train_list = [label_counts_train.get(l, 0) for l in LABELS]
majority = max(label_counts_train_list)
minority = min([x for x in label_counts_train_list if x > 0])
imbalance_ratio = round(majority / minority, 1)

# 2. Word length stats per category
import re

def word_count(text):
    return len(str(text).split())

df_train['word_count'] = df_train['question'].apply(word_count)
word_stats_by_label = {}
for lbl in LABELS:
    subset = df_train[df_train['label'] == lbl]['word_count']
    word_stats_by_label[lbl] = {
        'mean':   round(float(subset.mean()), 1),
        'median': round(float(subset.median()), 1),
        'max':    int(subset.max()),
        'min':    int(subset.min()),
        'std':    round(float(subset.std()), 1),
    }

print("Word stats by label:")
for lbl, stats in word_stats_by_label.items():
    print(f"  {lbl:8s}: mean={stats['mean']}, median={stats['median']}")

# 3. Most common words per category (top 5)
from collections import Counter

top_words_by_label = {}
for lbl in LABELS:
    texts = df_train[df_train['label'] == lbl]['clean'].tolist()
    all_words = ' '.join(texts).split()
    # Exclude the question word itself
    filtered = [w for w in all_words if w not in {'what','who','when','where','how','which','why'}]
    top_words_by_label[lbl] = [{'word': w, 'count': c}
                                 for w, c in Counter(filtered).most_common(8)]

print("\nTop words sample (What):", top_words_by_label['What'][:3])


# ─────────────────────────────────────────────────────────────────────────────
# CELL G: Assemble & Export Updated JSON
# ─────────────────────────────────────────────────────────────────────────────

# Load file hiện tại để không mất dữ liệu cũ
with open('plotly_data/text_ml_data.json', 'r', encoding='utf-8') as f:
    output = json.load(f)

# Cập nhật tournament với inference times
for row in output['tournament']:
    pname = row['pipeline']
    if pname in inference_times:
        row['inf_mean_ms'] = inference_times[pname]['mean_ms']
        row['inf_std_ms']  = inference_times[pname]['std_ms']

# Thêm tất cả dữ liệu mới
output['inference_times']        = inference_times
output['baselines']              = baselines
output['model_info']             = model_info
output['preprocessing_flow']     = preprocessing_flow
output['error_analysis_extended']= error_samples_extended
output['error_distribution']     = error_distribution
output['visual_eda'] = {
    'imbalance_ratio':    imbalance_ratio,
    'majority_class':     LABELS[label_counts_train_list.index(majority)],
    'minority_class':     LABELS[label_counts_train_list.index(minority)],
    'majority_count':     majority,
    'minority_count':     minority,
    'word_stats_by_label': word_stats_by_label,
    'top_words_by_label':  top_words_by_label,
}

# Ghi lại
with open('plotly_data/text_ml_data.json', 'w', encoding='utf-8') as f:
    json.dump(output, f, ensure_ascii=False, indent=2)

size_kb = os.path.getsize('plotly_data/text_ml_data.json') / 1024
print(f'\n✅ Updated JSON saved! Size: {size_kb:.1f} KB')
print(f'New keys added: {[k for k in output.keys()]}')


# ─────────────────────────────────────────────────────────────────────────────
# CELL H: Sanity Check
# ─────────────────────────────────────────────────────────────────────────────
with open('plotly_data/text_ml_data.json') as f:
    check = json.load(f)

print("=== ALL KEYS ===")
for k in check.keys():
    v = check[k]
    if isinstance(v, dict):
        print(f"  {k}: dict with {len(v)} entries")
    elif isinstance(v, list):
        print(f"  {k}: list with {len(v)} items")
    else:
        print(f"  {k}: {v}")

print("\n=== SPOT CHECKS ===")
print(f"  Baselines: {check['baselines']}")
print(f"  Imbalance ratio: {check['visual_eda']['imbalance_ratio']}")
print(f"  Preprocessing steps: {len(check['preprocessing_flow'])}")
print(f"  Error samples extended: {len(check['error_analysis_extended'])}")
sample_pipe = 'TF-IDF + Random Forest'
if sample_pipe in check['inference_times']:
    print(f"  Inference time ({sample_pipe}): {check['inference_times'][sample_pipe]['mean_ms']} ms/sample")

print("\n✅ All good — commit plotly_data/text_ml_data.json to GitHub!")

  Fitting & timing: TF-IDF + Logistic Regression...

/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:1184: FutureWarning: 'n_jobs' has no effect since 1.8 and will be removed in 1.10. You provided 'n_jobs=-1', please leave it unspecified.
  warnings.warn(msg, category=FutureWarning)

0.0002 ms/sample
  Fitting & timing: TF-IDF + Linear SVM... 0.0001 ms/sample
  Fitting & timing: TF-IDF + Random Forest... 0.0508 ms/sample
  Fitting & timing: BoW + Logistic Regression...

/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:1184: FutureWarning: 'n_jobs' has no effect since 1.8 and will be removed in 1.10. You provided 'n_jobs=-1', please leave it unspecified.
  warnings.warn(msg, category=FutureWarning)

0.0002 ms/sample
  Fitting & timing: BoW + Linear SVM... 0.0001 ms/sample
  Fitting & timing: BoW + Random Forest... 0.0655 ms/sample
  Fitting & timing: Word Emb + Logistic Regression...

/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:1184: FutureWarning: 'n_jobs' has no effect since 1.8 and will be removed in 1.10. You provided 'n_jobs=-1', please leave it unspecified.
  warnings.warn(msg, category=FutureWarning)

0.0012 ms/sample
  Fitting & timing: Word Emb + Linear SVM... 0.0004 ms/sample
  Fitting & timing: Word Emb + Random Forest... 0.0134 ms/sample

✅ Inference times done!

Summary (ms/sample):
  TF-IDF + Logistic Regression                   0.0002
  TF-IDF + Linear SVM                            0.0001
  TF-IDF + Random Forest                         0.0508
  BoW + Logistic Regression                      0.0002
  BoW + Linear SVM                               0.0001
  BoW + Random Forest                            0.0655
  Word Emb + Logistic Regression                 0.0012
  Word Emb + Linear SVM                          0.0004
  Word Emb + Random Forest                       0.0134
  DistilBERT (Fine-tuned)                        N/A (GPU)
Baselines:
  Baseline: Majority Class: Acc=44.97%  F1=7.75%
  Baseline: Random (Stratified): Acc=26.16%  F1=12.87%
Model info prepared for 10 pipelines
Preprocessing flow defined: 6 steps
Using DistilBERT predictions for error analysis

Total errors: 1 / 10570 (0.01%)

Error breakdown by true label:
label
Other    1
Name: count, dtype: int64

Most common confusion pairs:
label  pred  count
Other Which      1

Extended error samples collected: 1

Error distribution dict ready: 1 pairs
Word stats by label:
  What    : mean=9.9, median=9.0
  Who     : mean=9.0, median=8.0
  When    : mean=8.6, median=8.0
  Where   : mean=8.2, median=8.0
  How     : mean=9.9, median=9.0
  Which   : mean=10.3, median=10.0
  Why     : mean=9.6, median=9.0
  Other   : mean=11.6, median=11.0

Top words sample (What): [{'word': 'name', 'count': 2204}, {'word': 'type', 'count': 1522}, {'word': 'used', 'count': 1247}]

✅ Updated JSON saved! Size: 38.8 KB
New keys added: ['meta', 'label_distribution', 'eda_to_ml', 'feature_comparison', 'tournament', 'confusion_matrices', 'per_class_metrics', 'best_per_class', 'error_analysis', 'inference_times', 'baselines', 'model_info', 'preprocessing_flow', 'error_analysis_extended', 'error_distribution', 'visual_eda']
=== ALL KEYS ===
  meta: dict with 6 entries
  label_distribution: dict with 3 entries
  eda_to_ml: list with 5 items
  feature_comparison: dict with 3 entries
  tournament: list with 10 items
  confusion_matrices: dict with 10 entries
  per_class_metrics: dict with 10 entries
  best_per_class: list with 8 items
  error_analysis: list with 1 items
  inference_times: dict with 10 entries
  baselines: dict with 2 entries
  model_info: dict with 10 entries
  preprocessing_flow: list with 6 items
  error_analysis_extended: list with 1 items
  error_distribution: dict with 1 entries
  visual_eda: dict with 7 entries

=== SPOT CHECKS ===
  Baselines: {'Baseline: Majority Class': {'acc': 44.97, 'f1_macro': 7.75}, 'Baseline: Random (Stratified)': {'acc': 26.16, 'f1_macro': 12.87}}
  Imbalance ratio: 31.3
  Preprocessing steps: 6
  Error samples extended: 1
  Inference time (TF-IDF + Random Forest): 0.0508 ms/sample

✅ All good — commit plotly_data/text_ml_data.json to GitHub!

In [56]:
# CELL A - PATCH: Đo inference time thật của DistilBERT
import time

print("Đang đo inference time DistilBERT...")
REPEATS = 3
times = []
for _ in range(REPEATS):
    t = time.perf_counter()
    trainer.predict(tokenized_val)
    times.append((time.perf_counter() - t) / len(y_val) * 1000)

distil_mean = round(float(np.mean(times)), 4)
distil_std  = round(float(np.std(times)),  4)

print(f"DistilBERT inference: {distil_mean} ± {distil_std} ms/sample")

# Cập nhật vào inference_times (đang còn trong RAM)
inference_times['DistilBERT (Fine-tuned)'] = {
    'mean_ms':  distil_mean,
    'std_ms':   distil_std,
    'total_ms': round(distil_mean * len(y_val), 2),
    'note':     'Measured on Apple MPS (M-series GPU)',
}

# Cập nhật tournament trong output
for row in output['tournament']:
    if 'DistilBERT' in row['pipeline']:
        row['inf_mean_ms'] = distil_mean
        row['inf_std_ms']  = distil_std

# Ghi lại JSON
output['inference_times'] = inference_times
with open('plotly_data/text_ml_data.json', 'w', encoding='utf-8') as f:
    json.dump(output, f, ensure_ascii=False, indent=2)

print(f"✅ Updated! DistilBERT = {distil_mean} ms/sample")

Đang đo inference time DistilBERT...

/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/torch/utils/data/dataloader.py:1118: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/torch/utils/data/dataloader.py:1118: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/torch/utils/data/dataloader.py:1118: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

DistilBERT inference: 20.049 ± 0.2139 ms/sample
✅ Updated! DistilBERT = 20.049 ms/sample

In [57]:
# ── Fix n_pipelines + thêm error_analysis_traditional ────────────────────────
import json
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix, classification_report
import numpy as np

# Load file hiện tại
with open('plotly_data/text_ml_data.json', 'r', encoding='utf-8') as f:
    output = json.load(f)

# ── FIX 1: n_pipelines = 10 ───────────────────────────────────────────────────
output['meta']['n_pipelines'] = 10
print(f"✅ n_pipelines fixed: {output['meta']['n_pipelines']}")

# ── FIX 2: error_analysis_traditional (TF-IDF + Random Forest) ───────────────
print("\nRe-fitting TF-IDF + Random Forest for traditional error analysis...")
best_trad_clf = RandomForestClassifier(
    n_estimators=200, class_weight='balanced', n_jobs=-1, random_state=42
)
best_trad_clf.fit(X_train_tfidf, y_train)
y_trad_pred = best_trad_clf.predict(X_val_tfidf)

df_err_trad = df_val.copy()
df_err_trad['pred'] = y_trad_pred
errors_trad = df_err_trad[df_err_trad['label'] != df_err_trad['pred']]

total_trad_errors = len(errors_trad)
print(f"Total errors (TF-IDF + RF): {total_trad_errors} / {len(df_val)} "
      f"({total_trad_errors/len(df_val)*100:.2f}%)")

# Lấy 2 ví dụ mỗi confusion pair, tối đa 20 samples
trad_error_samples = []
for (true_lbl, pred_lbl), group in errors_trad.groupby(['label', 'pred']):
    for _, row in group.head(2).iterrows():
        trad_error_samples.append({
            'question': row['question'],
            'true':     true_lbl,
            'pred':     pred_lbl,
            'pair':     f"{true_lbl}→{pred_lbl}",
            'model':    'TF-IDF + Random Forest',
        })

trad_error_samples = sorted(trad_error_samples, key=lambda x: x['pair'])[:20]

# Phân phối lỗi theo pair (cho biểu đồ)
trad_error_dist = {}
for (true_lbl, pred_lbl), group in errors_trad.groupby(['label', 'pred']):
    trad_error_dist[f"{true_lbl}→{pred_lbl}"] = int(len(group))

# Lấy top 10 pairs nhiều lỗi nhất
trad_error_dist_top10 = dict(
    sorted(trad_error_dist.items(), key=lambda x: x[1], reverse=True)[:10]
)

print(f"\nTop confusion pairs (TF-IDF + RF):")
for pair, cnt in trad_error_dist_top10.items():
    print(f"  {pair}: {cnt}")

# Per-class report của TF-IDF + RF (đã có trong per_class_metrics, lấy lại)
LABELS = output['meta']['labels']
cr_trad = classification_report(
    y_val, y_trad_pred, labels=LABELS, zero_division=0, output_dict=True
)

# Thêm vào output
output['error_analysis_traditional']      = trad_error_samples
output['error_distribution_traditional']  = trad_error_dist_top10

# ── Ghi JSON ──────────────────────────────────────────────────────────────────
with open('plotly_data/text_ml_data.json', 'w', encoding='utf-8') as f:
    json.dump(output, f, ensure_ascii=False, indent=2)

import os
size_kb = os.path.getsize('plotly_data/text_ml_data.json') / 1024
print(f"\n✅ JSON updated! Size: {size_kb:.1f} KB")
print(f"Keys: {list(output.keys())}")
print(f"\nNew keys added:")
print(f"  error_analysis_traditional:     {len(output['error_analysis_traditional'])} samples")
print(f"  error_distribution_traditional: {len(output['error_distribution_traditional'])} pairs")

✅ n_pipelines fixed: 10

Re-fitting TF-IDF + Random Forest for traditional error analysis...
Total errors (TF-IDF + RF): 1466 / 10570 (13.87%)

Top confusion pairs (TF-IDF + RF):
  Other→What: 887
  What→Other: 159
  Other→Which: 153
  Other→How: 93
  Other→Who: 40
  Other→Where: 36
  When→What: 23
  Which→Other: 14
  Other→When: 13
  When→Who: 9

✅ JSON updated! Size: 43.3 KB
Keys: ['meta', 'label_distribution', 'eda_to_ml', 'feature_comparison', 'tournament', 'confusion_matrices', 'per_class_metrics', 'best_per_class', 'error_analysis', 'inference_times', 'baselines', 'model_info', 'preprocessing_flow', 'error_analysis_extended', 'error_distribution', 'visual_eda', 'error_analysis_traditional', 'error_distribution_traditional']

New keys added:
  error_analysis_traditional:     20 samples
  error_distribution_traditional: 10 pairs

In [63]:
!pip install "optimum[onnxruntime]" -q

In [64]:
# Convert model sang ONNX rồi push lên Hub
from transformers import AutoTokenizer
from optimum.onnxruntime import ORTModelForSequenceClassification

# Load model đã train
ort_model = ORTModelForSequenceClassification.from_pretrained(
    "hoangnguyenthe/squad-question-classifier",
    export=True  # tự động convert sang ONNX
)
tokenizer = AutoTokenizer.from_pretrained("hoangnguyenthe/squad-question-classifier")

# Push ONNX version lên Hub
ort_model.push_to_hub(
    "hoangnguyenthe/squad-question-classifier",
    use_auth_token=True
)
tokenizer.push_to_hub("hoangnguyenthe/squad-question-classifier")
print("✅ ONNX model pushed!")

ImportError: cannot import name 'FLAX_WEIGHTS_NAME' from 'transformers.utils' (/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/transformers/utils/__init__.py)

---
## Done!

Copy `plotly_data/text_ml_data.json` vào thư mục `plotly_data/` của repo GitHub.

Sau đó `text_ml.html` sẽ fetch file này và render toàn bộ charts/tables tự động.

**Tóm tắt output:**
- `meta` — hero stats (total docs, best acc, n pipelines...)
- `label_distribution` — phân phối 8 loại câu hỏi
- `eda_to_ml` — bảng liên kết EDA findings → ML decisions
- `feature_comparison` — acc/F1 của TF-IDF vs BoW vs Word Emb
- `tournament` — toàn bộ 9 pipelines xếp hạng
- `confusion_matrices` — ma trận nhầm lẫn cho mỗi pipeline
- `per_class_metrics` — precision/recall/F1 theo từng loại câu hỏi
- `best_per_class` — summary của model tốt nhất